const express=require('express')
const app=express()
app.use(express.json())
const blogRouter=require('./controllers/blogs')
const userRouter=require('./controllers/users')
const loginRouter = require('./controllers/login')
const middleware=require('./utils/middleware')
app.use(middleware.tokenExtractor)
app.use('/api/login', loginRouter)
app.use('/api/blogs',blogRouter)
app.use('/api/users',userRouter)
module.exports=app